### ISSUE TITLE
.has-error class for validation

### ISSUE THREAD

**Issue by Lowpoc** [marxjmoura/admin4b#18]
Add this configuration of the class for alerts in inputs, labels and hints.
```css
.has-error input {
  #border-color: #a94442;
  box-shadow: inset 0 1px 1px rgba(0, 0, 0, .075)
}

.has-error label,
.has-error .hint {
  color: #a94442;
}
```
